// client-svelte/src/lib/EditTodoItem.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import cancelIcon from "./cancel.icon.svg";
  import type { Todo, UpdateTodo } from "./todo.store";

  export let todo: Todo;

  const dispatch = createEventDispatcher<{
    cancel: undefined;
    update: [string, UpdateTodo];
  }>();

  let title = todo.title ?? ''

  const focus = (node:HTMLElement) => node.focus()

</script>

<form
  class="flex gap-3 flex-1"
  on:submit|preventDefault={() => dispatch("update", [todo.id, { title }])}
>
  <input
    use:focus
    class="input input-bordered w-full"
    type="text"
    bind:value={title}
    required
  />
  <button
    type="button"
    title="Cancel edit"
    on:click={() => dispatch('cancel')}
  >
    <img src={cancelIcon} alt="Cancel Icon" />
  </button>
</form>

// client-angular/src/app/edit-todo-item/edit-todo-item.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { Todo } from '../../types/todo.type';
import type { UpdateTodoEvent } from '../../types/update-todo-event.type';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';

@Component({
  selector: 'app-edit-todo-item',
  standalone: true,
  imports: [ReactiveFormsModule],
  templateUrl: './edit-todo-item.component.html',
})
export class EditTodoItemComponent {
  @Input({required: true}) todo!: Todo;
  @Output() cancel = new EventEmitter<undefined>()
  @Output() update = new EventEmitter<UpdateTodoEvent>()
  updateForm = new FormGroup({
    title: new FormControl<string>('', {
      validators: [Validators.required],
      nonNullable: true
    })
  })

  ngOnInit() {
    this.updateForm.setValue({title: this.todo.title})
  }

  onCancel() {
    this.cancel.emit()
  }

  onSubmit(event: Event) {
    event.preventDefault()
    this.update.emit([
      this.todo.id, 
      {title: this.updateForm.value.title!}
    ])
  }
}

<form class="flex gap-3 flex-1" [formGroup]="updateForm" (ngSubmit)="onSubmit($event)">
  <input type="text" required formControlName="title" class="input input-bordered w-full" />
  <button type="button" title="Cancel edit" (click)="onCancel()">
    <img src="/assets/cancel.icon.svg" alt="Cancel Icon" />
  </button>
</form>
