// client-angular/src/app/display-todo-item/display-todo-item.component.ts
import { Component, Input } from '@angular/core';
import type { Todo } from '../../types/todo.type';

@Component({
  selector: 'app-display-todo-item',
  standalone: true,
  imports: [],
  templateUrl: './display-todo-item.component.html',
  styleUrl: './display-todo-item.component.css'
})
export class DisplayTodoItemComponent {
  @Input() todo: Todo|null = null;

}

<div class="flex flex-1 w-full h-12 gap-3 items-center">
  <input #doneCheckbox type="checkbox" class="checkbox" [checked]="todo.done" (change)="onToggle()">
  <button (click)="onEdit()" class="truncate flex-1 text-left" [class.line-through]="todo.done"
    [class.text-base-300]="todo.done" title="Click to edit - {{ todo.title }}">
    {{todo.title}}
  </button>
  <button (click)="onDelete()">
    <img src="/assets/delete.icon.svg" alt="Delete icon" />
  </button>
</div>

// client-svelte/src/lib/DisplayTodoItem.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import deleteIcon from "./delete.icon.svg";
  import type { Todo, UpdateTodo } from "./todo.store";

  const dispatch = createEventDispatcher<{
    edit: undefined
    update: [string, UpdateTodo]
    delete: string
  }>()

  export let todo: Todo;
</script>

<div class="flex flex-1 w-full h-12 gap-3 items-center">
  <input
    type="checkbox"
    class="checkbox"
    checked={todo.done}
    on:change={() => dispatch("update", [todo.id, {done: !todo.done}])}
  />
  <button
    class="truncate flex-1 text-left"
    class:line-through={todo.done}
    class:text-base-300={todo.done}
    title={`Click to edit - ${todo.title}`}
    on:click={() => dispatch("edit")}
  >
    {todo.title}
  </button>
  <button on:click={() => dispatch("delete", todo.id)}>
    <img src={deleteIcon} alt="Delete icon" />
  </button>
</div>
