// client-angular/src/app/todo-list/todo-list.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Todo } from '../../types/todo.type';
import { FormControl, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import type { CreateTodo } from '../../types/create-todo.type';
import type { UpdateTodoEvent } from '../../types/update-todo-event.type';
import type { TodoId } from '../../types/todo-id.type';

import { TodoItemComponent } from '../todo-item/todo-item.component';

@Component({
  selector: 'app-todo-list',
  standalone: true,
  imports: [ReactiveFormsModule, TodoItemComponent],
  templateUrl: './todo-list.component.html',
})
export class TodoListComponent {
  @Input() todos: Todo[] = []
  @Output() create = new EventEmitter<CreateTodo>()
  @Output() update = new EventEmitter<UpdateTodoEvent>()
  @Output() delete = new EventEmitter<TodoId>()

  createForm = new FormGroup({
    title: new FormControl<string>('', {
      validators: [Validators.required],
      nonNullable: true
    })
  })

  onSubmit(event: Event) {
    event.preventDefault()
    this.create.emit({
      title: this.createForm.value.title!,
      done: false 
    })
    this.createForm.reset()
  }

  onUpdate(event: UpdateTodoEvent) { this.update.emit(event) }
  
  onDelete(id: TodoId) { this.delete.emit(id) }
}

<div class="flex flex-col gap-3">
  <form 
    class="flex gap-2 flex-col sm:flex-row"
    [formGroup]="createForm"
    (ngSubmit)="onSubmit($event)"
  >
    <input
      class="input input-bordered"
      type="text"
      placeholder="Type the Todo title here"
      required
      formControlName="title"
    >
    <button 
      type="submit" 
      class="btn"
      [disabled]="!createForm.valid"
    >
      Add new Todo
    </button>
  </form>
  <ul>
  @for (todo of todos; track todo.id) {
    <app-todo-item [todo]="todo" (delete)="onDelete($event)" (update)="onUpdate($event)"/>
  }
</ul>
</div>

// client-svelte/src/lib/TodoList.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import type { CreateTodo, Todo } from "./todo.store";
  import TodoItem from "./TodoItem.svelte";

  export let todos: Todo[];

  const dispatch = createEventDispatcher<{ create: CreateTodo }>();

  let title = "";

  const handleCreate = () => {
    dispatch("create", { title, done: false });
    title = "";
  };
</script>

<div class="flex flex-col gap-3">
  <form
    class="flex gap-2 flex-col sm:flex-row" 
    on:submit|preventDefault={handleCreate}
  >
    <input
      class="input input-bordered"
      type="text"
      placeholder="Type the Todo title here"
      required
      bind:value={title}
    />
    <button type="submit" class="btn">Add new Todo</button>
  </form>
  <ul>
    {#each todos as todo}
      <TodoItem {todo} on:update on:delete />
    {/each}
  </ul>
</div>
