// client-svelte/src/lib/DisplayTodoItem.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import deleteIcon from "./delete.icon.svg";
  import type { Todo, UpdateTodo } from "./todo.store";

  const dispatch = createEventDispatcher<{
    edit: undefined
    update: [string, UpdateTodo]
    delete: string
  }>()

  export let todo: Todo;
</script>

<div class="flex flex-1 w-full h-12 gap-3 items-center">
  <input
    type="checkbox"
    class="checkbox"
    checked={todo.done}
    on:change={() => dispatch("update", [todo.id, {done: !todo.done}])}
  />
  <button
    class="truncate flex-1 text-left"
    class:line-through={todo.done}
    class:text-base-300={todo.done}
    title={`Click to edit - ${todo.title}`}
    on:click={() => dispatch("edit")}
  >
    {todo.title}
  </button>
  <button on:click={() => dispatch("delete", todo.id)}>
    <img src={deleteIcon} alt="Delete icon" />
  </button>
</div>

// client-react/src/components/DisplayTodoItem.tsx
import { Todo, UpdateTodo } from "../todo-api"

const DeleteIcon = () => <svg xmlns="http://www.w3.org/2000/svg" height="16" width="14" viewBox="0 0 448 512"><path d="M135.2 17.7L128 32H32C14.3 32 0 46.3 0 64S14.3 96 32 96H416c17.7 0 32-14.3 32-32s-14.3-32-32-32H320l-7.2-14.3C307.4 6.8 296.3 0 284.2 0H163.8c-12.1 0-23.2 6.8-28.6 17.7zM416 128H32L53.2 467c1.6 25.3 22.6 45 47.9 45H346.9c25.3 0 46.3-19.7 47.9-45L416 128z" /></svg>

type DisplayTodoItemProps = {
  todo: Todo,
  onUpdate: (updates: UpdateTodo) => void
  onEdit: () => void
  onDelete: () => void
}

export default function DisplayTodoItem({
  todo,
  onUpdate,
  onEdit,
  onDelete
}: DisplayTodoItemProps) {
  const doneClass = "line-through text-base-300"

  return (
    <div className="flex flex-1 w-full h-12 gap-3 items-center">
    <input
      type="checkbox"
      className="checkbox"
      checked={todo.done}
      onChange={() => onUpdate({done: !todo.done})}
    />
    <button 
      className={`truncate flex-1 text-left ${todo.done ? doneClass: ''}`} 
      title={`Click to edit - ${todo.title}`}
      onClick={onEdit}
    >
      {todo.title}
    </button>
    <button 
      title="Delete todo"
      onClick={() => onDelete()}
    >
      <DeleteIcon />
    </button>
  </div>

  ) 
}
