// client-svelte/src/lib/TodoItem.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  import type { Todo, UpdateTodo } from "./todo.store";
  import EditTodoItem from "./EditTodoItem.svelte";
  import DisplayTodoItem from "./DisplayTodoItem.svelte";

  export let todo: Todo;

  let editing = false;

  const dispatch = createEventDispatcher<{
    update: [string, UpdateTodo];
  }>();

</script>

<li class="flex gap-3 text-lg max-w-sm">
  {#if editing}
    <EditTodoItem
      {todo}
      on:cancel={() => (editing = false)}
      on:update={(e) => {
        dispatch("update", e.detail);
        editing = false;
      }}
    />
  {:else}
    <DisplayTodoItem
      {todo}
      on:delete
      on:edit={() => (editing = true)}
      on:update
    />
  {/if}
</li>

// client-react/src/components/TodoItem.tsx
import { useState } from "react"
import type { Todo, UpdateTodo } from "../todo-api"
import EditTodoItem from "./EditTodoItem"
import DisplayTodoItem from "./DisplayTodoItem"

type TodoItemProps = {
  todo: Todo,
  onUpdate: (updates: UpdateTodo) => void
  onDelete: () => void
}
export default function TodoItem({ 
  todo, 
  onUpdate, 
  onDelete 
}: TodoItemProps) {
  const [editing, setEditing] = useState(false)

  const handleSave = (updates: UpdateTodo) => {
    setEditing(false)
    onUpdate(updates)
  }

  return (
    <li className="flex gap-3 text-lg max-w-sm">
      {editing ? (
        <EditTodoItem 
          todo={todo}
          onSave={handleSave}
          onCancel={() => setEditing(false)}
        />
      ) : (
        <DisplayTodoItem 
          todo={todo}
          onDelete={onDelete}
          onEdit={() => setEditing(true)}
          onUpdate={onUpdate}
        />
      )}
    </li>
  )
}
