// client-svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import {
    todos,
    loading,
    error,
    type UpdateTodo,
    type CreateTodo,
  } from "./lib/todo.store.js";
  import TodoList from "./lib/TodoList.svelte";

  onMount(async () => {
    await todos.readAll();
  });

  const handleUpdate = async (event: CustomEvent<[string, UpdateTodo]>) => {
    const [id, updates] = event.detail;
    await todos.update(id, updates);
  };

  const handleCreate = async (event: CustomEvent<CreateTodo>) => {
    const todo = event.detail;
    await todos.create(todo);
  };

  const handleDelete = async (event: CustomEvent<string>) => {
    const id = event.detail;
    await todos.delete(id);
  };
</script>

<div class="container m-0 sm:m-3 text-lg">
  {#if $loading}
    <div class="fixed top-0 right-0 loading loading-dots loading-lg"></div>
  {/if}
  <main class="flex justify-center">
    <div class="flex flex-col gap-2">
      <div>
        <h1 class="text-4xl font-bold mb-0 mt-2">Todo APP</h1>
        <h2 class="text-xl text-zinc-500 font-bold mt-0 mb-2">with Svelte</h2>
      </div>
      {#if $error}
        Ooops, something went wrong.
      {/if}
      {#if $todos && !$error}
        <div>
          <TodoList
            todos={$todos}
            on:update={handleUpdate}
            on:create={handleCreate}
            on:delete={handleDelete}
          />
        </div>
      {/if}
    </div>
  </main>
</div>

<style>
</style>

// client-angular/src/app/app.component.ts
import { Component, inject } from '@angular/core';
import { Todo } from '../types/todo.type';
import { TodoListComponent } from './todo-list/todo-list.component';

import type { CreateTodo } from '../types/create-todo.type';
import type { UpdateTodoEvent } from '../types/update-todo-event.type';
import type { TodoId } from '../types/todo-id.type';

import { TodoService } from '../services/todo/todo.service';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [TodoListComponent],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  title = 'app';
  loading = false;
  error: Error | null = null;
  todos: Todo[] = []
  todoService = inject(TodoService)

  constructor() {
    this.loading = true
    this.todoService.readAll().subscribe({
      next: (todos) => { this.todos = todos },
      error: (error) => { this.error = error },
      complete: () => { this.loading = false }
    })
  }

  onCreate(todo: CreateTodo) {
    this.loading = true
    this.todoService.create(todo).subscribe({
      next: (created) => { this.todos.push(created) },
      error: (error) => { this.error = error },
      complete: () => { this.loading = false }
    })
  }

  onUpdate([id, updates]: UpdateTodoEvent) {
    this.loading = true
    this.todoService.update(id, updates).subscribe({
      next: (updated) => {
        this.todos = this.todos.map(
          (todo) =>
            todo.id === updated.id
              ? updated
              : todo
        )
      },
      error: (error) => { this.error = error },
      complete: () => { this.loading = false }
    })
  }

  onDelete(id: TodoId) {
    this.loading = true
    this.todoService.delete(id).subscribe({
      next: (deleted) => {
        this.todos = this.todos.filter(
          (todo) => todo.id !== deleted.id
        )
      },
      error: (error) => { this.error = error },
      complete: () => { this.loading = false }
    })
  }
}

<div class="container m-0 sm:m-3 text-lg">
  @if (loading) {
  <div class="fixed top-0 right-0">Loading...</div>
  }

  <main class="flex jusfity-center">
    <div class="flex flex-col gap-2">
      <div>
        <h1 class="text-4xl fond-bold mb-0 mt-2">
          Todo APP
        </h1>
        <h2 class="text-xl text-zinc-500 fond-bold mt-0 mb-2">
          with Angular
        </h2>
      </div>
      @if (error) {
      <div>Something went wrong: {{error.message}}</div>
      }
      <div>
        <app-todo-list [todos]="todos" (create)="onCreate($event)" (delete)="onDelete($event)"
          (update)="onUpdate($event)" />
      </div>
    </div>
  </main>
</div>
