// client-svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import {
    todos,
    loading,
    error,
    type UpdateTodo,
    type CreateTodo,
  } from "./lib/todo.store.js";
  import TodoList from "./lib/TodoList.svelte";
  import ErrorMessage from "./Error.svelte";
  import Loading from "./Loading.svelte";

  onMount(async () => {
    await todos.readAll();
  });

  const handleUpdate = async (event: CustomEvent<[string, UpdateTodo]>) => {
    const [id, updates] = event.detail;
    await todos.update(id, updates);
  };

  const handleCreate = async (event: CustomEvent<CreateTodo>) => {
    const todo = event.detail;
    await todos.create(todo);
  };

  const handleDelete = async (event: CustomEvent<string>) => {
    const id = event.detail;
    await todos.delete(id);
  };
</script>

<div class="container m-0 sm:m-3 text-lg">
  {#if $loading}
    <div class="fixed top-0 right-0">
      <Loading />
    </div>
  {/if}
  <main class="flex justify-center">
    <div class="flex flex-col gap-2">
      <div>
        <h1 class="text-4xl font-bold mb-0 mt-2">Todo APP</h1>
        <h2 class="text-xl text-zinc-500 font-bold mt-0 mb-2">with Svelte</h2>
      </div>
      {#if $error}
        <ErrorMessage message={$error.message} />
      {/if}
      {#if $todos && !$error}
        <div>
          <TodoList
            todos={$todos}
            on:update={handleUpdate}
            on:create={handleCreate}
            on:delete={handleDelete}
          />
        </div>
      {/if}
    </div>
  </main>
</div>

<style>
</style>

// client-react/src/App.tsx
import Error from "./components/Error"
import Loading from "./components/Loading"
import TodoList from "./components/TodoList"
import { CreateTodo, Todo, useTodo } from "./todo-api"

function App() {
  const { todos, error, loading, update, remove, create } = useTodo()

  const handleUpdate = async (id: string, updates: Partial<Todo>) => {
    await update(id, updates)
  }

  const handleCreate = async (todo: CreateTodo) => {
    await create(todo)
  }

  const handleDelete = async (id: string) => {
    await remove(id)
  }

  return (
    <div className="container m-0 sm:m-3 text-lg">
      <div className="fixed top-0 right-0">
        {loading && <Loading />}
      </div>
      <main className="flex justify-center">
        <div className="flex flex-col gap-2">
          <div>
            <h1 className="text-4xl font-bold mb-0 mt-2">TODO App</h1>
            <h2 className="text-xl text-zinc-500 font-bold mt-0 mb-2">with React Client</h2>
          </div>
            {error && <Error message={error.message} />}
            {todos && !error &&(
              <div>
                <TodoList
                  todos={todos}
                  onUpdate={handleUpdate}
                  onAdd={handleCreate}
                  onDelete={handleDelete}
                />
              </div>
            )}
        </div>
      </main>
    </div>
  )
}

export default App
